### ISSUE TITLE
More than 100% melee uptime on certain fights

### ISSUE THREAD

**Issue by ryancraigdavis** [ryancraigdavis/WCL_DK_Analyzer#35]
**Describe the bug**
Unclear what is going on but a bug causing +100% uptime on melee and diseases

**To Reproduce**
https://classic.warcraftlogs.com/reports/qwydVBK8W61v9L3J#fight=15&type=damage-done&source=20

**Expected behavior**
100% should be the cap

**Screenshots**
![Screenshot_20240810_091202](https://github.com/user-attachments/assets/98f1fa71-e553-444b-a890-d2a27e1dc795)

**Comment by lime-green** [comment]
Addressed in https://github.com/ryancraigdavis/WCL_DK_Analyzer/pull/38
