### ISSUE TITLE
Melee uptime calculation

### ISSUE THREAD

**Issue by Gapearz** [ryancraigdavis/WCL_DK_Analyzer#7]
In quite few logs next issue was observed:
- Melee uptime % is quite low, even tho the character in question seems to be attacking for the whole duration of the fight.

Example log (saw multiple logs with similar behavior in the last week):
https://classic.warcraftlogs.com/reports/yXfk6nLzr47j1TqW#fight=43&source=39
Char: Takadk

**Comment by ryancraigdavis** [comment]
This may be due to the number of misses/parries.
See the miss/parry/dodge calculation in WCL

**Comment by Gapearz** [comment]
I don't think its due to miss/parry. Few of my own logs have miss/parry (just due to boss mechanic), but the analyzer still states that melee uptime is 100%

**Comment by lime-green** [comment]
the max swing speed was previously set to 2.5s. Ideally we detect the weapon type (1h vs 2h) and use a swing speed of 4s or something if it's a 2h -- I can probably get to this this week if no-one else does

**Comment by ryancraigdavis** [comment]
Oh yeah, I had totally forgotten about this - whichever of us gets to it first
I need to get some basic Frost functionality in but I don't want that to delay getting the extension up and running
